### ISSUE TITLE
[Bug]:  Error with yarn build/dev.  Module not found: Error: Can't resolve '../pages/ResetPassword.vue' 

### ISSUE THREAD

**Issue by lambrohan** [vuestorefront/shopify#62]
### Expected Behavior

Should build successfully and run a dev server.

### Actual Behavior

`ERROR in ./.nuxt/router.js
Module not found: Error: Can't resolve '../pages/ResetPassword.vue' in '/media/rohan/WORK/tinkering/vue-store-shopify/.nuxt'
 @ ./.nuxt/router.js 127:24-129:3
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js`

### Steps to reproduce

1. Create a new project with `vsf init` and select `shopify` integration.
2. Install node dependencies `yarn` and run the dev server `yarn dev` 

### What version of shopify integration are you using?

1.0.0

### What version of Node.js are you using?

14.17.5

### What browser (and version) are you using?

Brave Version 1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)

### What operating system (and version) are you using?

Pop!_OS 21.04 64 bit

### Relevant log output

```shell
ERROR in ./.nuxt/router.js
Module not found: Error: Can't resolve '../pages/ResetPassword.vue' in '/media/rohan/WORK/tinkering/vue-store-shopify/.nuxt'
 @ ./.nuxt/router.js 127:24-129:3
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

 FATAL  Nuxt build error                                                                                                                                           12:37:43

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:110:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

error Command failed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lambrohan** [comment]
Sorry. This was not an integration but the storefront issue.

Read More
https://github.com/vuestorefront/vue-storefront/issues/6196
